services:
  db:
    image: mysql:8.0.43
    container_name: precision_db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "precision_schema_v2"
    ports:
      - "3306:3306"